import { MenuItem } from '../types';

// Örnek menü verileri (Sample menu data)
export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Pizza kategorisi (Pizza category)
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Klasik domates sosu, mozzarella peyniri ve fesleğen',
    price: 89.90,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    available: true,
    preparationTime: 15,
  },
  {
    id: '2',
    name: 'Pepperoni Pizza',
    description: 'Domates sosu, mozzarella vebol pepperoni',
    price: 99.90,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    available: true,
    preparationTime: 15,
  },
  {
    id: '3',
    name: 'Karışık Pizza',
    description: 'Sucuk, sosis, mantar, biber, zeytin',
    price: 109.90,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    available: true,
    preparationTime: 18,
  },

  // 🍔 Burger kategorisi - Riverside Burgers Özel Menü (Burger category - Riverside Burgers Special Menu)
  {
    id: '4',
    name: 'Riverside Classic',
    description: '200gr dana eti, cheddar peyniri, marul, domates, turşu, özel Riverside sosu',
    price: 89.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    available: true,
    preparationTime: 12,
  },
  {
    id: '5',
    name: 'Double Riverside',
    description: '2x200gr dana eti, çift cheddar, karamelize soğan, barbekü sosu',
    price: 129.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400',
    available: true,
    preparationTime: 15,
  },
  {
    id: '6',
    name: 'Crispy Chicken Burger',
    description: 'Çıtır tavuk, marul, domates, ranch sos, jalapeno',
    price: 84.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400',
    available: true,
    preparationTime: 12,
  },
  {
    id: '6a',
    name: 'BBQ Bacon Burger',
    description: 'Dana eti, çıtır bacon, cheddar, barbekü sosu, soğan halkası',
    price: 99.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
    available: true,
    preparationTime: 14,
  },
  {
    id: '6b',
    name: 'Mushroom Swiss Burger',
    description: 'Dana eti, İsviçre peyniri, sote mantar, truffle mayonez',
    price: 94.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400',
    available: true,
    preparationTime: 13,
  },
  {
    id: '6c',
    name: 'Veggie Burger',
    description: 'Sebze köftesi, avokado, marul, domates, vegan mayonez',
    price: 79.90,
    category: 'burger',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400',
    available: true,
    preparationTime: 11,
  },

  // Pasta kategorisi (Pasta category)
  {
    id: '7',
    name: 'Fettuccine Alfredo',
    description: 'Kremalı parmesan sosu ile',
    price: 69.90,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400',
    available: true,
    preparationTime: 15,
  },
  {
    id: '8',
    name: 'Spaghetti Bolognese',
    description: 'Kıymalı domates sosu',
    price: 64.90,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    available: true,
    preparationTime: 15,
  },
  {
    id: '9',
    name: 'Penne Arrabiata',
    description: 'Acılı domates sosu',
    price: 59.90,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    available: true,
    preparationTime: 12,
  },

  // Salata kategorisi (Salad category)
  {
    id: '10',
    name: 'Sezar Salata',
    description: 'Marul, kruton, parmesan, sezar sos',
    price: 49.90,
    category: 'salad',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    available: true,
    preparationTime: 8,
  },
  {
    id: '11',
    name: 'Akdeniz Salatası',
    description: 'Domates, salatalık, zeytin, beyaz peynir',
    price: 44.90,
    category: 'salad',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    available: true,
    preparationTime: 8,
  },

  // Tatlı kategorisi (Dessert category)
  {
    id: '12',
    name: 'Tiramisu',
    description: 'İtalyan klasiği, kahve ve mascarpone',
    price: 54.90,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
    available: true,
    preparationTime: 5,
  },
  {
    id: '13',
    name: 'Cheesecake',
    description: 'Kremalı peynir tatlısı, çilek soslu',
    price: 49.90,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=400',
    available: true,
    preparationTime: 5,
  },
  {
    id: '14',
    name: 'Çikolatalı Sufle',
    description: 'Sıcak çikolata sufle, vanilyalı dondurma',
    price: 59.90,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
    available: true,
    preparationTime: 12,
  },

  // İçecek kategorisi (Drink category)
  {
    id: '15',
    name: 'Kola',
    description: 'Soğuk kola (330ml)',
    price: 15.90,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    available: true,
    preparationTime: 2,
  },
  {
    id: '16',
    name: 'Limonata',
    description: 'Ev yapımı limonata',
    price: 24.90,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=400',
    available: true,
    preparationTime: 3,
  },
  {
    id: '17',
    name: 'Türk Kahvesi',
    description: 'Geleneksel Türk kahvesi',
    price: 19.90,
    category: 'drink',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400',
    available: true,
    preparationTime: 5,
  },
];

// Kategori isimleri (Category names)
export const CATEGORY_NAMES = {
  pizza: 'Pizza',
  burger: 'Burger',
  pasta: 'Makarna',
  salad: 'Salata',
  dessert: 'Tatlı',
  drink: 'İçecek',
};

